### ISSUE TITLE
Original Source And Build Method

### ISSUE THREAD

**Issue by ghost** [adafruit/Adafruit_nRF51822_Flasher#3]
This is a great project and has been very helpful.  But OpenOCD is open source and you have not indicated how to rebuild that source from scratch.  This is not a distribution of source, but of binaries.  

I don't care about GPL requirements, but I really need the source, with the revision history(git), and the method used to build this, so I can fix issues that come up.  

Can you please provide?

**Comment by ladyada** [comment]
openocd supports nrf51822 natively, we have made not changes to it?
source is here http://openocd.org/
