### ISSUE TITLE
Flashing problem with Rasp 2 GPIO

### ISSUE THREAD

**Issue by trungdn** [adafruit/Adafruit_nRF51822_Flasher#4]
I try to flash a firmware for Adafruit Bluefruit LE UART Friend module
https://www.adafruit.com/product/2479
I made the connection same as instruction.
SWD (BLE) connect to PIN24(GPIO)
SWC (BLE) connect to PIN25(GPIO)
FCR (Factory Reset - BLE) connect to PIN18(GPIO)
GND (BLE) connect to GND (GPIO)

The comment I use 
sudo python flash.py --jtag=rpigpio --board=blefriend32 --softdevice=8.0.0 --bootloader=2 --firmware=0.6.5

But no luck, the flash was failed
Here is the log.txt

BCM2835 GPIO nums: swclk = 25, swdio = 24
BCM2835 GPIO config: srst = 18
srst_only separate srst_gates_jtag srst_push_pull connect_deassert_srst
swd
0
cortex_m reset_config sysresetreq
adapter speed: 1000 kHz
Info : BCM2835 GPIO JTAG/SWD bitbang driver
Info : SWD only mode enabled (specify tck, tms, tdi and tdo gpios to add JTAG mode)
Info : clock speed 1001 kHz
Info : SWD IDCODE 0x0004d414
Error: Target not examined yet
in procedure 'reset'
in procedure 'ocd_bouncer'

Could you please help me to find the problems?
Thank you very much.

**Comment by ladyada** [comment]
rpigpio doesnt work well with nrf52 - use a jlink! :)

**Comment by hristost** [comment]
I could not flash with RPi either. Would a stlink/v2 work in place of jlink?
